### ISSUE TITLE
this is worded horribly and i dont understand what i should do 

### ISSUE THREAD

**Issue by uhhhggg** [Fireflywater/TerraTech_BuffBlocks#3]

**Comment by Fireflywater** [comment]
I need more information than that. What are you trying to do?
Installing the mod? Use Terratech Mod Manager to download and install, you'll also need the NuTerra Block Injector.
Need blocks that use this mod? Look around the Terratech Forums.
Rafs has a couple. https://forum.terratechgame.com/index.php?threads/rafs-custom-blocks-and-skins.20154/ See the second post for Download.

**Comment by uhhhggg** [comment]
i am trying to install the test block

**Comment by Fireflywater** [comment]
Install via Mod Manager, and install Block Injector too. Then download this repository to get /CustomBlocks/FFW_BuffBlock_Test/ and put that folder in CustomBlocks.
Alsooo I think I missed up, because you need FFW_Recycled_Block.obj in the folder too, which is found in /TerraTech_BuffBlocks-1_1_1-master/CustomBlocks/FFW_BuffBlock_Test/
The test blocks aren't that good, they're just... well, test blocks.

**Comment by uhhhggg** [comment]
so i have it installed but the blocks are invisible, dont have models and i cant change them

**Comment by Fireflywater** [comment]
Yeah, that sounds like the .obj is missing. It's my bad, you can find it in /TerraTech_BuffBlocks-1_1_1-master/CustomBlocks/FFW_BuffBlock_Test/ , just add it to the same folder the .jsons are in.

**Comment by uhhhggg** [comment]
i did that and they are still invisible?

**Comment by Fireflywater** [comment]
Okay, I know the issue, I'm really sorry about that/this. Uh, you know that forum link up there? I used some of Rafs' blocks for placeholders. 
Download that, find the zip that's called "GT_BasicBlocks", and put that folder in the Custom Blocks folder. That *should* have all the texture and models that the placeholder block uses.

**Comment by uhhhggg** [comment]
alright so the block now exists but i cant seem to do anything with it

**Comment by Fireflywater** [comment]
Can't put them on a tech? The "MK2 TEST TEST" should boost the fire rate of your weapons and increase pickup range of things like SCUs.

**Comment by uhhhggg** [comment]
so that works but the rest dont

**Comment by Fireflywater** [comment]
The #2 should increase the speed of wheels but reduce their braking abilities, and the #3 should remove the anchor requirement for things like SCUs and Factories (turning things into "mobile" things).

**Comment by uhhhggg** [comment]
no its not those, theres also a bunch of other ones like "FFW_BuffBlock_Weapon_Cooldown_Temp"

**Comment by Fireflywater** [comment]
Those are old and are no longer supported. They use the old "mk1" version of the mod, which isn't installed by the mod manager. 
Only the "MK2 TEST TEST", "MK2 #2 TEST TEST", and "MK2 #3 TEST TEST" are functional.
So... please delete all the .jsons starting with "FFW_BuffBlock_" and keep the ones that start with "FFW_BuffBlockMk2_"

**Comment by uhhhggg** [comment]
done and i now have no issues anymore so thanks!

**Comment by Fireflywater** [comment]
I apologize for the inconvenience.
